modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/extra-gems/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="extragems:amethyst"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ExtraGems_NEO.json"
displayURL="https://minecraft.curseforge.com/projects/extra-gems"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod adds a few new gems for tools, weapons, armor, blocks and more to your world!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

