modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/extra-gems/issues"

[[mods]]
modId="extragems"
version="2.1.4"
displayName="ExtraGems"
itemIcon="extragems:amethyst"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ExtraGems.json"
displayURL="https://minecraft.curseforge.com/projects/extra-gems"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''This mod adds a few new gems for tools, weapons, armor, blocks and more to your world!'''

[[dependencies.extragems]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extragems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
